mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
    faqs_view,
    about_view,
    color_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

from store.views import (
    cart_view,
    checkout_view,
    reservation_view,
    order_summary_view,
    reservation_summary_view,
    reservations_list_view,
    orders_list_view,
    set_reservation_as_received_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_screen_view, name='home'),
    path('store/', include('store.urls', 'store')),
    path('slider/', include('slider.urls', 'slider')),
    
    path('login/', login_view, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('account/', account_view, name='account'),
    path('orders_list/', orders_list_view, name='orders_list'),
    path('reservations_list/', reservations_list_view, name='reservations_list'),
    path('set_reservation_as_received/<str:reservation_id>/', set_reservation_as_received_view, name='set_reservation_as_received'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('social-auth/', include('social_django.urls', namespace='social')),

    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('reservation/', reservation_view, name='reservation'),
    path('order_summary/', order_summary_view, name='order_summary'),
    path('reservation_summary/', reservation_summary_view, name='reservation_summary'),

    path('faqs/', faqs_view, name='faqs'),
    path('about/', about_view, name='about'),
    path('colors/', color_view, name='colors'),
    
    
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', store_view, name='store'),
    path('create_product/', create_product_view, name='create_product'),
    path('<slug>/', view_product_view, name='view_product'),
    path('<slug>/edit', edit_product_view, name='edit_product'),
    path('<slug>/add_comment', add_comment_view, name='add_comment'),
    path("<int:comment_id>/confirm_comment/", confirm_comment_view, name='confirm_comment'),
    path("<int:comment_id>/add_reply/", add_reply_view, name='add_reply'),
    path("<slug>/delete", delete_product_view, name='delete_product'),
    path('<slug>/delete_product_confirmed', delete_product_confirmed_view, name='delete_product_confirmed'),
    path("<slug>/add_to_cart/", add_to_cart_view, name='add_to_cart'),
    path("<slug>/rm_from_cart/", rm_from_cart_view, name='rm_from_cart'),
    path("<slug>/rm_cart_item/", rm_cart_item_view, name='rm_cart_item'),
]

store/models.py
from django.db import models

from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
from hashid_field import HashidAutoField

from account.models import (
    Account
)


def upload_location(instance, filename, **kwargs):
    file_path = 'store/{title}/{filename}'.format(
        title=slugify(instance.title), filename=filename
    )
    return file_path

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=False, blank=False, unique=True)
    description = models.CharField(max_length=5000, null=False, blank=True, default='')
    
    authors = models.CharField(max_length=200, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location)

    price = models.FloatField(null=False, blank=False)
    added_by = models.ForeignKey(Account, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    is_deleted = models.BooleanField(null=False, blank=True, default=False)
    containsNotConfirmedComments = models.PositiveIntegerField(null=False, blank=True, default=0)
    
    def __str__(self):
        return f'ID: {str(self.product_id)},  TITLE: "{self.title}", ADDED_BY: {self.added_by.email}'
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url=''
        return url
    
# prevent keeping the image after the post was deleted
@receiver(post_delete, sender=Product)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

# execute action before it was saved
def pre_save_product_receiever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)

pre_save.connect(pre_save_product_receiever, sender=Product)







class Cart(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=False, blank=False)
    products = models.ManyToManyField(Product, through='CartItem')

    def __str__(self):
        return f'ID: {self.id},  USER: {self.user.email}'
    
    @property
    def get_cart_total(self):
        # btw dir(self) helped to solve 'self do not have orderitem_set parameter' by printing all 
        # parameters afer self.*something* and by removing values that was in both sets i found 
        # that I should use cartitem_set istead of orderitem_set, but still i don't know where it come from...
        cartitems = self.cartitem_set.all()
        total = sum([item.get_total for item in cartitems])
        return total
    
    @property
    def get_cart_items(self):
        cartitems = self.cartitem_set.all()
        total = sum([item.quantity for item in cartitems])
        return total

    def create_order(self, order_data):
        print('in create...')
        order = Order.objects.create(
            user=self.user,
            **order_data
        )
        
        for cart_item in self.cartitem_set.all():
            print('\tcreating OrderItem...')
            order_item = OrderItem.objects.create(
                order=order,
                product=cart_item.product,
                quantity=cart_item.quantity
            )
            order_item.save()
            print('\t...OrderItem created!', order_item)
            print()
        print('...created!')
        return order
    
    
    def create_reservation(self, reservation_data):
        print('in create...')
        reservation = Reservation.objects.create(
            user=self.user,
            **reservation_data
        )
        
        for cart_item in self.cartitem_set.all():
            print('\tcreating ReservationItem...')
            reservation_item = ReservationItem.objects.create(
                reservation=reservation,
                product=cart_item.product,
                quantity=cart_item.quantity
            )
            reservation_item.save()
            print('\t...OrderItem created!', reservation_item)
            print()
        print('...created!')
        return reservation
    

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'CART ID: {self.cart.id},  USER: {self.cart.user.email},  PRODUCT: {self.product.product_id},  Quantity: {self.quantity}'
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    










class Order(models.Model):
    id = HashidAutoField(primary_key=True, min_length=16, salt="OrderSalt_skhjfks")
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=False, blank=False)
    products = models.ManyToManyField(Product, through='OrderItem')
    order_date = models.DateTimeField(auto_now_add=True)

    
    first_name = models.CharField(max_length=200, null=False, blank=False)
    last_name = models.CharField(max_length=200, null=False, blank=False)
    address = models.CharField(max_length=400, null=False, blank=False)
    country = models.CharField(max_length=200, null=False, blank=False)
    city = models.CharField(max_length=200, null=False, blank=False)
    zip_code = models.CharField(max_length=6, null=False, blank=False)

    card_name = models.CharField(max_length=400, null=False, blank=False)
    card_id = models.CharField(max_length=19, null=False, blank=False)
    card_exp = models.CharField(max_length=5, null=False, blank=False)
    card_cvv = models.CharField(max_length=3, null=False, blank=False)

    delivered = models.BooleanField(null=False, blank=True, default=False)

    def __str__(self):
        # return f'ID: {str(self.id)[-4:]},  USER: {self.user.email},  STATUS: {"finished" if self.delivered else "in shipment"}'
        return f'ID: {self.id},  USER: {self.user.email},  STATUS: {"finished" if self.delivered else "in shipment"}'

    def set_to_delivered(self):
        self.delivered = True
        
    @property
    def get_order_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

        
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        # return f'ID: {str(self.order.id)[-4:]},  USER: {self.order.user.email},  PRODUCT: {self.product.product_id},  Quantity: {self.quantity}'
        return f'ORDER ID: {self.order.id},  USER: {self.order.user.email},  PRODUCT: {self.product.product_id},  Quantity: {self.quantity}'
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    








class Reservation(models.Model):
    id = HashidAutoField(primary_key=True, min_length=16, salt="ReservationSalt_fjhgikds")
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=False, blank=False)
    products = models.ManyToManyField(Product, through='ReservationItem')
    reservation_date = models.DateTimeField(auto_now_add=True)
    
    first_name = models.CharField(max_length=200, null=False, blank=False)
    last_name = models.CharField(max_length=200, null=False, blank=False)
    address = models.CharField(max_length=400, null=False, blank=False)
    country = models.CharField(max_length=200, null=False, blank=False)
    city = models.CharField(max_length=200, null=False, blank=False)
    zip_code = models.CharField(max_length=6, null=False, blank=False)

    received = models.BooleanField(null=False, blank=True, default=False)

    def __str__(self):
        # return f'ID: {str(self.id)[-4:]},  USER: {self.user.email},  STATUS: {"recived" if self.received else "waiting"}'
        return f'ID: {self.id},  USER: {self.user.email},  STATUS: {"recived" if self.received else "waiting"}'

    def set_to_received(self):
        self.received = True
        
    @property
    def get_reservation_total(self):
        reservation_items = self.reservationitem_set.all()
        total = sum([item.get_total for item in reservation_items])
        return total

        
class ReservationItem(models.Model):
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        # return f'ID: {str(self.reservation.id)[-4:]},  USER: {self.reservation.user.email},  PRODUCT: {self.product.product_id},  Quantity: {self.quantity}'
        return f'RESERVATION ID: {self.reservation.id},  USER: {self.reservation.user.email},  PRODUCT: {self.product.product_id},  Quantity: {self.quantity}'
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total



class Comment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='comments', null=False, blank=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', null=False, blank=False)
    content = models.TextField()
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return f'target {self.product} by {self.user}'

class Reply(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='replies', null=False, blank=False)
    parentComment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies', null=False, blank=False)
    content = models.TextField()

    def __str__(self):
        return f'target {self.parentComment} by {self.user}'
    

store/forms.py
from django import forms

from store.models import (
    Product,
    Order,
    Reservation
)

class CreateProductForm(forms.ModelForm):

    # how form should look like
    class Meta:
        model = Product
        # fields that user are able to setup while filling the form
        fields = ['title', 'authors', 'description', 'image', 'price']

    def getTitle(self):
        return self.cleaned_data.get('title')
        
class UpdateProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['title', 'authors', 'description', 'image', 'price']

    def save(self, commit=True):
        product = self.instance
        product.title = self.cleaned_data['title']
        product.authors = self.cleaned_data['authors']
        product.description = self.cleaned_data['description']
        product.price = self.cleaned_data['price']

        if self.cleaned_data['image']:
            product.image = self.cleaned_data['image']

        if commit:
            product.save()
        return product
        


class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'country', 'city', 'zip_code', 'card_name', 'card_id', 'card_exp', 'card_cvv']


class ReservationForm(forms.ModelForm):
    
    class Meta:
        model = Reservation
        fields = ['first_name', 'last_name', 'address', 'country', 'city', 'zip_code']

store/templates/store/checkout.html
{% extends 'base.html' %}

{% block content %}



<div class="container">
    <div class="row">
        <div class="col">
            <a class="btn btn-outline-secondary text-left" href="{% url 'cart' %}">&#8592; Back</a>
        </div>
        <div class="col">
            <h1 class="display-4 flex-grow-1 text-center">Checkout</h1>
        </div>
        <div class="col">
        </div>
    </div>
    <br>
    
    <form class="needs-validation create-form" method="post" enctype="multipart/form-data" novalidate> {% csrf_token %}
        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <!-- <span class="badge badge-secondary badge-pill">3</span> -->
                </h4>
                <ul class="list-group mb-3">
                    {% for item in cart_items %}
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">{{item.quantity}} x {{item.product.title}}</h6>
                            <small class="text-muted">{{item.product.authors}}</small> <br>
                            <!-- <small class="text-muted">{{item.quantity}}x {{item.product.price|floatformat:2}}zł</small> -->
                        </div>
                        <!-- <span class="text-muted">{{item.product.price|floatformat:2}}zł</span> -->
                        <span class="text-muted">{{item.get_total|floatformat:2}}zł</span>
                    </li>
                    {% endfor %}
                    <!-- <li class="list-group-item d-flex justify-content-between bg-light">
                    <div class="text-success">
                        <h6 class="my-0">Promo code</h6>
                        <small>EXAMPLECODE</small>
                    </div>
                    <span class="text-success">-$5</span>
                </li> -->
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total</span>
                        <strong>{{cart.get_cart_total|floatformat:2}}zł</strong>
                    </li>
                </ul>

                <!-- <form class="card p-2">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Promo code">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-secondary">Redeem</button>
                    </div>
                </div>
            </form> -->
                <!-- <hr class="mb-4"> -->
                <div style="text-align: right;">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Submit Your Order</button>
                </div>
            </div>
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Billing address</h4>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="id_first_name">First name</label>
                        <input type="text" class="form-control" name="first_name" id="id_first_name" placeholder="" value="{{default.first_name}}" required>
                        <div class="invalid-feedback">
                            Valid first name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_last_name">Last name</label>
                        <input type="text" class="form-control" name="last_name" id="id_last_name" placeholder="" value="{{default.last_name}}" required>
                        <div class="invalid-feedback">
                            Valid last name is required.
                        </div>
                    </div>
                </div>

                
                <div class="mb-3">
                    <label for="username">Username</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div>
                        <input type="text" class="form-control" id="username" placeholder="Username"
                            value="{{request.user.username}}" required>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="email">Email</label>
                    <div class="input-group">
                        <!-- <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div> -->
                        <input type="email" class="form-control" id="email" placeholder="you@example.com"
                            value="{{request.user.email}}" readonly required disabled>
                        <div class="invalid-feedback">
                            Please enter a valid email address for shipping updates.
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="id_address">Address</label>
                    <input type="text" class="form-control" name="address" id="id_address" placeholder="1234 Main St" value="{{default.address}}" required>
                    <div class="invalid-feedback">
                        Please enter your shipping address.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5 mb-3">
                        <label for="id_country">Country</label>
                        <input type="text" class="form-control" name="country" id="id_country" placeholder="" value="{{default.country}}" required>
                        <div class="invalid-feedback">
                            Country required.
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="id_city">City</label>
                        <input type="text" class="form-control" name="city" id="id_city" placeholder="" value="{{default.city}}" required>
                        <div class="invalid-feedback">
                            City required.
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="id_zip_code">Zip</label>
                        <input type="text" class="form-control" name="zip_code" id="id_zip_code" placeholder="XX-XXX" value="{{default.zip}}" required>
                        <div class="invalid-feedback">
                            Zip code required.
                        </div>
                    </div>
                </div>
                <hr class="mb-4">


                <h4 class="mb-3">Payment</h4>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="id_card-name">Name on card</label>
                        <input type="text" class="form-control" name="card_name" id="id_card-name" placeholder="Janek Kolwalski" value="{{default.card_name}}" required>
                        <small class="text-muted">Full name as displayed on card</small>
                        <div class="invalid-feedback">
                            Name on card is required
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_card_id">Credit card number</label>
                        <input type="text" class="form-control" name="card_id" id="id_card_id" placeholder="1234 5678 9012 3456" value="{{default.card_id}}" required>
                        <div class="invalid-feedback">
                            Credit card number is required
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <label for="id_card_exp">Expiration</label>
                        <input type="text" class="form-control" name="card_exp" id="id_card_exp" placeholder="12/20" value="{{default.card_exp}}" required>
                        <div class="invalid-feedback">
                            Expiration date required
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="id_card_cvv">CVV</label>
                        <input type="text" class="form-control" name="card_cvv" id="id_card_cvv" placeholder="123" value="{{default.card_cvv}}" required>
                        <div class="invalid-feedback">
                            Security code required
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- <script>
    (function () {
        'use strict';

        window.addEventListener('load', function () {
            var forms = document.getElementsByClassName('needs-validation');

            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script> -->


{% endblock content %}

store/templates/store/view_product.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="mx-auto text-center d-flex align-items-center">
        <div class="flex-grow-1 d-flex justify-content-start">
            <a class="btn btn-outline-secondary" href="{% url 'store:store' %}">
                &#8592; Back
            </a>
        </div>
        {% if request.user.is_staff %}
        <div class="d-flex justify-content-end">
            <a class="btn btn-outline-warning add-btn" href="{% url 'store:edit_product' product.slug %}" style="margin-right: 10px;">
                Edit Product
            </a>
            <a class="btn btn-outline-danger add-btn" href="{% url 'store:delete_product' product.slug %}">
                Delete Product
            </a>
        </div>
        {% else %}
        <div class="d-flex justify-content-end">
            <a class="btn btn-outline-light" href="{% url 'store:add_to_cart' product.slug %}">
                Add To Cart
            </a>
        </div>
        {% endif %}
        <!-- <h1 class="display-4 flex-grow-1">Product</h1> -->
    </div>
    <br>
    
    {% if success_update_message %}
        <h3 style="color: green; text-align: center;"> {{success_update_message}} </h3>
    {% endif %}
	<div class="mx-auto text-center d-flex align-items-center">
        <img class="thumbnail" src="{{product.image.url}}" title="{{product.title}}" style="width: 600px; height: 800px; object-fit: contain;">
        <div class="display-4 flex-grow-1">
            <h1 class="display-5 flex-grow-1">{{product.title}}</h1>
            <h3 class="flex-grow-1" 
                style="font-size: 20px; font-weight: lighter; color: rgba(255,255,255, 0.5); word-wrap: break-word; white-space: pre-wrap;">
                Authors: {{product.authors}}
            </h3>
            <div style="text-align: right;">
                <h3 class="display-7">{{product.price|floatformat:2}}zł</h3>
            </div>
        </div>
    </div>
    <br>
    <p class="lead text-muted" style="text-align: left; margin-left: 50px; margin-right: 50px; word-wrap: break-word; white-space: pre-wrap;">
        {{product.description}}        
        {% comment %} {{product.description|safe}} {% endcomment %}
    </p>
    <br>

    <div class="border p-3">
        <div class="border p-3">
            {% if request.user.is_authenticated %}
                <div class="add-comment">
                    <form method="post" action="{% url 'store:add_comment' product.slug %}">
                        {% csrf_token %}
                        <textarea class="form-control" type="text" rows="5" name="content" required
                            placeholder="Comment content..."></textarea>
                        <button class="btn border p-2" type="submit"> Add comment </button>
                    </form>
                </div>
            {% else %}
                <p> To add a comment 
                    <a href="{% url 'login' %}">Login</a> or 
                    <a href="{% url 'register' %}">Sign-up</a>
                </p>
            {% endif %}
        </div>
        {% for comment in comments %}
            <div class="border p-3">
                <strong>{{ comment.user.email }}</strong>
                <p>{{ comment.content }}</p>
                
                {% comment %}
                    visible only if comment was not confirmed
                    and only staff can see not confirmed comments
                {% endcomment %}
                {% if comment.confirmed is False and request.user.is_staff %}
                    <form method="post" action="{% url 'store:confirm_comment' comment.id %}">
                        {% csrf_token %}
                        <button class="btn border p-2" type="submit"> Confirm Comment </button>
                    </form>
                {% endif %}
                <br>
                
                {% if comment.replies.all.count != 0 or comment.confirmed is False %}
                    {% comment %}
                        visible only if comment was not confirmed
                        and only staff can see not confirmed comments
                    {% endcomment %}
                    {% if request.user.is_staff %}
                        {% if comment.confirmed is False %}
                            <div class="border p-3">
                                <div class="reply-form">
                                    <form method="post" action="{% url 'store:add_reply' comment.id %}">
                                        {% csrf_token %}
                                        <textarea class="form-control" type="text" rows="5" name="content" required
                                            placeholder="Reply content..."></textarea>
                                        <button class="btn border p-2" type="submit"> Reply </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                        
                    {% else %}
                        <p><small>Not confirmed</small></p>
                    {% endif %}

                    {% if comment.replies.all %}
                        {% for reply in comment.replies.all %}
                            <div class="border p-3">
                                <p>{{ reply.user.email }}</p>
                                <p>{{ reply.content }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
        {% empty %}
            <p>No comments</p>
        {% endfor %}

    </div>
    
</div>

{% endblock content %}