mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
    faqs_view,
    about_view,
    color_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

from store.views import (
    cart_view,
    checkout_view,
    reservation_view,
    order_summary_view,
    reservation_summary_view,
    reservations_list_view,
    orders_list_view,
    set_reservation_as_received_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_screen_view, name='home'),
    path('store/', include('store.urls', 'store')),
    path('slider/', include('slider.urls', 'slider')),
    
    path('login/', login_view, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('account/', account_view, name='account'),
    path('orders_list/', orders_list_view, name='orders_list'),
    path('reservations_list/', reservations_list_view, name='reservations_list'),
    path('set_reservation_as_received/<str:reservation_id>/', set_reservation_as_received_view, name='set_reservation_as_received'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('social-auth/', include('social_django.urls', namespace='social')),

    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('reservation/', reservation_view, name='reservation'),
    path('order_summary/', order_summary_view, name='order_summary'),
    path('reservation_summary/', reservation_summary_view, name='reservation_summary'),

    path('faqs/', faqs_view, name='faqs'),
    path('about/', about_view, name='about'),
    path('colors/', color_view, name='colors'),
    
    
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

slider/urls.py
from django.urls import path
from slider.views import (
    slider_view,
    manage_sliders_view,

    upload_image,
    admin_slider,
    change_slider_view,
    user_slider,
)

app_name = 'slider'

urlpatterns = [
    # path('', slider_view, name='slider'),
    # path('manage_sliders/', manage_sliders_view, name='manage_sliders'),
    # path('slider/', slider_view, name='slider'),

    path('upload/', upload_image, name='upload_image'),
    path('admin/slider/', admin_slider, name='admin_slider'),
    path('change_slider/<int:slider_image_id>', change_slider_view, name='change_slider'),
    path('slider/', user_slider, name='user_slider'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', store_view, name='store'),
    path('create_product/', create_product_view, name='create_product'),
    path('<slug>/', view_product_view, name='view_product'),
    path('<slug>/edit', edit_product_view, name='edit_product'),
    path('<slug>/add_comment', add_comment_view, name='add_comment'),
    path("<int:comment_id>/confirm_comment/", confirm_comment_view, name='confirm_comment'),
    path("<int:comment_id>/add_reply/", add_reply_view, name='add_reply'),
    path("<slug>/delete", delete_product_view, name='delete_product'),
    path('<slug>/delete_product_confirmed', delete_product_confirmed_view, name='delete_product_confirmed'),
    path("<slug>/add_to_cart/", add_to_cart_view, name='add_to_cart'),
    path("<slug>/rm_from_cart/", rm_from_cart_view, name='rm_from_cart'),
    path("<slug>/rm_cart_item/", rm_cart_item_view, name='rm_cart_item'),
]

templates/snippets/header/middle_auth.html
{% load static %}

{% if request.user.is_superuser %} <!-- superuser -->
    <li><a href="{% url 'home' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Home</a></li>
    <li><a href="{% url 'colors' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Colors</a></li>
    <li><a href="\admin\" class="nav-link px-2 header-text" style="color: var(--color-3)">Admin</a></li>

{% elif request.user.is_admin %} <!-- admin -->
    <li><a href="{% url 'home' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Home</a></li>
    <li><a href="{% url 'colors' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Colors</a></li>

{% elif request.user.is_staff %} <!-- staff -->
    <li><a href="{% url 'home' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Home</a></li>
    <!-- <li><a href="" class="nav-link px-2 header-text" style="color: var(--color-3)">Slider</a></li> -->
    <li><a href="{% url 'slider:upload_image' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">upload_image</a></li>
    <li><a href="{% url 'slider:admin_slider' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">admin_slider</a></li>
    <li><a href="{% url 'store:store' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Store</a></li>
    <li><a href="{% url 'reservations_list' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Reservations</a></li>
    <li><a href="{% url 'orders_list' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Orders</a></li>

{% else %} <!-- customer -->
    <li><a href="{% url 'home' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Home</a></li>
    <li><a href="{% url 'slider:user_slider' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">user_slider</a></li>
    <li><a href="{% url 'store:store' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">Store</a></li>
    <li><a href="{% url 'faqs' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">FAQs</a></li>
    <li><a href="{% url 'about' %}" class="nav-link px-2 header-text" style="color: var(--color-3)">About</a></li>

{% endif %}

templates/snippets/header/middle_default.html
{% load static %}

<li><a href="{% url 'home' %}" class="nav-link px-2" style="color: var(--color-3)">Home</a></li>
<li><a href="{% url 'store:store' %}" class="nav-link px-2" style="color: var(--color-3)">Store</a></li>
<li><a href="{% url 'faqs' %}" class="nav-link px-2" style="color: var(--color-3)">FAQs</a></li>
<li><a href="{% url 'about' %}" class="nav-link px-2" style="color: var(--color-3)">About</a></li>

templates/snippets/header/right_auth.html
{% load static %}

{% if request.user.is_superuser %} <!-- superuser -->
    <a href="{% url 'account' %}" class="btn btn-outline-primary">Account</a>

{% elif request.user.is_admin %} <!-- admin -->
    <a href="{% url 'account' %}" class="btn btn-outline-primary">Account</a>

{% elif request.user.is_staff %} <!-- staff -->
    <a href="{% url 'account' %}" class="btn btn-outline-primary">Account</a>

{% else %} <!-- customer -->
    <a href="{% url 'cart' %}" class="btn">
        <i class="fa-solid fa-cart-shopping"
            style="color: lightgray; font-size: 30px; transform: translateY(2px); "></i>
    </a>
    <a href="{% url 'account' %}" class="btn btn-primary">Account</a>

{% endif %}

<button type="button" data-toggle="modal" data-target="#logoutModal"
class="btn btn-outline-danger me-2" >Logout</button>

<!-- Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <i class="fa-solid fa-arrow-right-from-bracket"
                        style="color: rgb(220, 53, 69); font-size: 20px;"></i>
                    &nbsp; Logout
                </h5>
            </div>
            <div class="modal-body text-center">
                &nbsp; Are you sure to logout?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a href="{% url 'logout' %}" type="button" class="btn btn-outline-danger">Logout</a>
            </div>
        </div>
    </div>
</div>

templates/snippets/header/right_default.html
{% load static %}

<!-- not registered user -->
<a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Login</a>
<a href="{% url 'register' %}" class="btn btn-primary">Sign-up</a>