mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
    faqs_view,
    about_view,
    color_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

from store.views import (
    cart_view,
    checkout_view,
    reservation_view,
    order_summary_view,
    reservation_summary_view,
    reservations_list_view,
    orders_list_view,
    set_reservation_as_received_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_screen_view, name='home'),
    path('store/', include('store.urls', 'store')),
    path('slider/', include('slider.urls', 'slider')),
    
    path('login/', login_view, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('account/', account_view, name='account'),
    path('orders_list/', orders_list_view, name='orders_list'),
    path('reservations_list/', reservations_list_view, name='reservations_list'),
    path('set_reservation_as_received/<str:reservation_id>/', set_reservation_as_received_view, name='set_reservation_as_received'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('social-auth/', include('social_django.urls', namespace='social')),

    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('reservation/', reservation_view, name='reservation'),
    path('order_summary/', order_summary_view, name='order_summary'),
    path('reservation_summary/', reservation_summary_view, name='reservation_summary'),

    path('faqs/', faqs_view, name='faqs'),
    path('about/', about_view, name='about'),
    path('colors/', color_view, name='colors'),
    
    
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

slider/urls.py
from django.urls import path
from slider.views import (
    slider_view,
    manage_sliders_view,

    upload_image,
    admin_slider,
    change_slider_view,
    user_slider,
)

app_name = 'slider'

urlpatterns = [
    # path('', slider_view, name='slider'),
    # path('manage_sliders/', manage_sliders_view, name='manage_sliders'),
    # path('slider/', slider_view, name='slider'),

    path('upload/', upload_image, name='upload_image'),
    path('admin/slider/', admin_slider, name='admin_slider'),
    path('change_slider/<int:slider_image_id>', change_slider_view, name='change_slider'),
    path('slider/', user_slider, name='user_slider'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', store_view, name='store'),
    path('create_product/', create_product_view, name='create_product'),
    path('<slug>/', view_product_view, name='view_product'),
    path('<slug>/edit', edit_product_view, name='edit_product'),
    path('<slug>/add_comment', add_comment_view, name='add_comment'),
    path("<int:comment_id>/confirm_comment/", confirm_comment_view, name='confirm_comment'),
    path("<int:comment_id>/add_reply/", add_reply_view, name='add_reply'),
    path("<slug>/delete", delete_product_view, name='delete_product'),
    path('<slug>/delete_product_confirmed', delete_product_confirmed_view, name='delete_product_confirmed'),
    path("<slug>/add_to_cart/", add_to_cart_view, name='add_to_cart'),
    path("<slug>/rm_from_cart/", rm_from_cart_view, name='rm_from_cart'),
    path("<slug>/rm_cart_item/", rm_cart_item_view, name='rm_cart_item'),
]

slider/models.py
from django.db import models

class SliderImage(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='slider_images/')
    isInSlider = models.BooleanField()

slider/forms.py
from django import forms
from .models import SliderImage

class SliderImageForm(forms.ModelForm):
    class Meta:
        model = SliderImage
        fields = ['title', 'description', 'image', 'isInSlider']

slider/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.conf import settings


from store.models import (
    Product,
    Cart,
    CartItem,
    Order,
    OrderItem,
    Reservation,
    ReservationItem,
)
from store.forms import (
    CreateProductForm,
    UpdateProductForm,
    OrderForm,
    ReservationForm,
)
from account.models import (
    Account,
)

def slider_view(request):
    return render(request, "store/store.html", {})


def manage_sliders_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated or not user.is_staff:
        return redirect('must_authenticate')
    
    # get all sliders
    # products = Product.objects.all()
    # products = Product.objects.filter(is_deleted=False)
    
    # for each slider read all products
    # for product in products:
    #     product.title = product.title[:40] + '...' if len(product.title) > 40 else product.title
    #     product.authors = product.authors[:50] + '...' if len(product.authors) > 50 else product.authors

    context = {'sliders': ['slider1', 'slider2']}
    return render(request, "manage_sliders.html", context)




# from django.shortcuts import render, redirect
from .models import SliderImage
from .forms import SliderImageForm

# import pprint

def upload_image(request):
    if request.method == 'POST':
        form = SliderImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('slider:upload_image')
    else:
        form = SliderImageForm()
    return render(request, 'upload_image.html', {'form': form})

def admin_slider(request):
    print("slider loaded, request:")
    # pp = pprint.PrettyPrinter(indent=4)
    # pp.pprint(vars(request))
    sliderImages = SliderImage.objects.all();
    print(sliderImages)
    return render(request, 'admin_slider.html', {'slider_images': sliderImages})

def change_slider_view(request, slider_image_id):
    user = request.user
    if not user.is_authenticated or not user.is_staff:
        return redirect('must_authenticate')
    
    sliderImage = get_object_or_404(SliderImage, id=slider_image_id)
    if request.method == "POST":
        isInSliderCheckBox = request.POST.get('isInSliderCheckBox') is not None
        print(isInSliderCheckBox)
        sliderImage.isInSlider = False if isInSliderCheckBox is None else isInSliderCheckBox
        sliderImage.save()

    return redirect('slider:admin_slider')

def user_slider(request):
    sliderImages = SliderImage.objects.filter(isInSlider = True);
    print(sliderImages)
    return render(request, 'user_slider.html', {'slider_images': sliderImages})

slider/templates/admin_slider.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
<h1>Admin Slider</h1>
{% csrf_token %}
{% for slider_image in slider_images %}
<form method="post" action="{% url 'slider:change_slider' slider_image.id %}">
    {% csrf_token %}
    <div class="border p-3">
        <img src="{{ slider_image.image.url }}" alt="{{ slider_image.title }}" width="150">
        <p>title: {{ slider_image.title }}</p>
        <p>description: {{ slider_image.description }}</p>
        <label for="id_isInSlider">is in slider:</label>
        <input id="id_isInSlider" type="checkbox" name="isInSliderCheckBox"
                {% if slider_image.isInSlider %}checked{% endif %}>
        <br>
        <button class="btn border p-2" type="submit"> Save </button>
    </div>
{% endfor %}

</div> 

{% endblock content %}

slider/templates/manage_sliders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="text-center">
        <label style="margin-bottom: 10px;">
            Current Slider:
        </label>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown button
            </button>
            <ul class="dropdown-menu">
                {% for slider in sliders %}
                <li><a class="dropdown-item" href="#">{{slider}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
    
</div>
{% endblock content %}

slider/templates/slider.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="text-center">
        <label style="margin-bottom: 10px;">
            Current Slider:
        </label>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown button
            </button>
            <ul class="dropdown-menu">
                {% for slider in sliders %}
                <li><a class="dropdown-item" href="#">{{slider}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
    
</div>
{% endblock content %}

slider/templates/slider_component.html
{% load static %}

<div class="container">
    Slider component
</div>

slider/templates/upload_image.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
</div>
{% endblock content %}

slider/templates/user_slider.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="object-list">
    {% for slider_image in slider_images %}
    <div class="object-item">
        <img src="{{ slider_image.image.url }}" alt="{{ slider_image.title }}">
        <div class="description">
        </div>
    </div>
    {% endfor %}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script>
    $(document).ready(function(){
        // $('.slider').slick({
        //     infinite: true,
        //     slidesToShow: 3,
        //     slidesToScroll: 1,
        //     autoplay: true,
        //     autoplaySpeed: 2000,
        //     responsive: [
        //         {
        //             breakpoint: 1024,
        //             settings: {
        //                 slidesToShow: 2,
        //                 slidesToScroll: 1,
        //                 infinite: true,
        //             }
        //         },
        //         {
        //             breakpoint: 600,
        //             settings: {
        //                 slidesToShow: 1,
        //                 slidesToScroll: 1
        //             }
        //         }
        //     ]
        // });

        // function setEqualHeight() {
        //     var maxHeight = 0;
        //     $('.slider .card').each(function() {
        //         var cardHeight = $(this).outerHeight();
        //         if (cardHeight > maxHeight) {
        //             maxHeight = cardHeight;
        //         }
        //     });
        //     $('.slider .card').css('height', maxHeight + 'px');
        // }

        // setEqualHeight();
        // $(window).resize(setEqualHeight);
    });
</script>
{% endblock content %}